import { Quote } from './quote';
import { JobTitle } from './job-title';
import { Location } from './location';
import { Article } from './article';

export class Artist {
  id?: number;
  name?: string;
  alias?: string;
  additionalNames?: string;
  birthDate?: string;
  deathDate?: string;
  activeSince: number;
  activeUntil?: number;
  birthPlace?: number;
  deathPlace?: number;
  residencePlace?: number;
  gender?: string = 'OTHER';
  jobTitle?: number;
  jobRoles?: string[] = [];
  relatedTo?: Artist;
  biography?: string;
  country?: number;
  nationality?: string;
  instruments?: number[] = [];
  awards: number[] = [];
  albums: number[] = [];
  collaborations: number[] = [];
  affiliation: number;
  studyAt: number;
  label?: number;
  genres: number[] = [];
  email?: string;
  website?: string;
  isniCode?: string;
  spotify?: string;
  appleMusic?: string;
  soundCloud?: string;
  deezer?: string;
  youtube?: string;
  instagram?: string;
  viberate?: string;
  facebook?: string;
  twitter?: string;
  tiktok?: string;
  libOfCongress?: string;
}
