import { ImageFile } from './image-file';
export class Artist {
  id?: string;
  name?: string;
  alias?: string;
  additionalNames?: string;
  imageFile?: ImageFile;
  birthDate?: string;
  deathDate?: string;
  activeSince: number;
  activeUntil?: number;
  birthPlaceId?: string;
  deathPlaceId?: string;
  residencePlaceId?: string;
  gender?: string = 'OTHER';
  jobTitleId?: string;
  jobRoles?: string[] = [];
  relatedArtists: string[] = [];
  biography?: string;
  nationality?: string;
  instrumentsIds?: string[] = [];
  awardsIds: string[] = [];
  albumsIds: string[] = [];
  collaborations: string[] = [];
  organizationId: string;
  studyAtId: string;
  recordLabelId?: string;
  genresIds: string[] = [];
  email?: string;
  website?: string;
  isniCode?: string;
  spotify?: string;
  appleMusic?: string;
  soundCloud?: string;
  deezer?: string;
  youtube?: string;
  instagram?: string;
  viberate?: string;
  reverbNation?: string;
  facebook?: string;
  twitter?: string;
  tiktok?: string;
  libOfCongress?: string;
}
