name: CI

on:
  push:
    branches: [main, dev]
    pull_request: false
    workflows_dispatch: true
jobs:
  deploy:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
      - name: Install & Build
        run: npm install && npm run build
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: 'dist'
          target: '/var/www/cubanmusic'
          rm: true
